// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH6lLbEzsgSjMgksosCEY6kDdenz_WdFU',
    appId: '1:523570126625:web:7d6c575397644314832860',
    messagingSenderId: '523570126625',
    projectId: 'fashionapp-a8b36',
    authDomain: 'fashionapp-a8b36.firebaseapp.com',
    storageBucket: 'fashionapp-a8b36.appspot.com',
    measurementId: 'G-BDL8V2FYST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaJlDfWA7T566mPvgZUEDAUnxEN9obKYo',
    appId: '1:523570126625:android:69f93f62ec7014ac832860',
    messagingSenderId: '523570126625',
    projectId: 'fashionapp-a8b36',
    storageBucket: 'fashionapp-a8b36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBONLTR2FXV4Y7tastVhDjkWHxW9EjUt0g',
    appId: '1:523570126625:ios:fad7ad155d01f4e0832860',
    messagingSenderId: '523570126625',
    projectId: 'fashionapp-a8b36',
    storageBucket: 'fashionapp-a8b36.appspot.com',
    iosBundleId: 'com.example.fashionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBONLTR2FXV4Y7tastVhDjkWHxW9EjUt0g',
    appId: '1:523570126625:ios:7ab823bc9b39cb09832860',
    messagingSenderId: '523570126625',
    projectId: 'fashionapp-a8b36',
    storageBucket: 'fashionapp-a8b36.appspot.com',
    iosBundleId: 'com.example.fashionApp.RunnerTests',
  );
}
